# -*- mode: ruby -*-
# vi: set ft=ruby :

#set number hosts
$kaf_mach = 5

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "start.sh"

#create kafka hosts

   (1..$kaf_mach).each do |i|
        config.vm.define "kaf#{i}" do |kaf|
#         kaf.vm.network  "public_network", ip: "192.168.1.#{10+i}"
         kaf.vm.network "private_network", ip: "192.168.50.#{10+i}"
         kaf.vm.hostname = "kaf#{i}"  
         kaf.vm.provider "virtualbox" do |vb|
                vb.memory = "1500"
         end
        end
   end
end
